### REWARDS CALCULATION SCRIPT SETTINGS ###
# Public key of the block producer. Example B62qjhiEXP45KEk8Fch4FnYJQ7UMMfiR3hq9ZeMUZ8ia3MbfEteSYDg
VALIDATOR_ADDRESS: B62qjhiEXP45KEk8Fch4FnYJQ7UMMfiR3hq9ZeMUZ8ia3MbfEteSYDg
# To ensure we only get blocks from the current staking epoch as the ledger may be different. Example 8
STAKING_EPOCH_NUMBER: 8
# Commission from regular blocks (non supercharged). Example 0.05 = 5%
VALIDATOR_FEE: 0.07
# Commission for supercharged blocks. This commission is divided among all delegates whose tokens are 100% unlocked
VALIDATOR_FEE_SP: 0.05
# Percentage that the validator takes from tokens delegated from Foundation. Example 0.05 == 5%
VALIDATOR_FEE_FOUNDATION: 0.05
# The first slot in the epoch from which rewards will be counted.
# Do not touch these values if you do not understand what you are doing!
FIRST_BLOCK_HEIGHT: 0
# Last slot in the epoch from which rewards will be counted.
# Do not touch these values if you do not understand what you are doing!
LATEST_BLOCK_HEIGHT: 0
# The minimum number of confirmations after which the block is considered canonical
CONFIRMATIONS_NUM: 15

### PAYOUT SCRIPT PARAMETERS ###
# GRAPHQL hostname or ip. Example: 127.0.0.1
GRAPHQL_HOST: 127.0.0.1
# GRAPHQL port. Example: 3085
GRAPHQL_PORT: 3085
# This is the line that will be included in the MEMO when rewards are paid
VALIDATOR_NAME: c29r3
# Password from the wallet imported into Mina daemon
WALLET_PASSWORD: YOUR_WALLET_PASSWORD
# 10000000 NANOMINA == 0.001 MINA
DEFAULT_TX_FEE: 10000000
# Imported wallet address from which you send rewards
SEND_FROM_ADDRESS: B62qoiQhNWjwFkfCVBpkDTYytifftoYQB9qJ3z6X4d58ocxmiwUQY8U
# Time in seconds, during which the script will check the sent transactions. Default: 1200 sec = 20 min. Example: 1200
# If within the allotted time it is not possible to confirm all transactions, then the script saves unsuccessful transactions to a file
TX_CHECK_TIMER_SECONDS: 1200
